### PR TITLE
Fix flaky cli-test.js test case on Windows, round two

### LINKED ISSUE #1030: Flaky test: "when using language hook handler and spawning the server and handler is killed before execution should return with status 1"
Another annoying flaky little fellow in the Windows test suite:
```
1) CLI when called with arguments when using language hook handler and spawning the server and handler is killed before execution should return with status 1:
      AssertionError: expected 7 to equal 1
      + expected - actual
      -7
      +1
      
      at Context.it (C:\projects\dredd\test\integration\cli\cli-test.js:166:56)
      at callFn (C:\projects\dredd\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\projects\dredd\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\projects\dredd\node_modules\mocha\lib\runner.js:428:10)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:534:12
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:348:14)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:358:7
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\projects\dredd\node_modules\mocha\lib\runner.js:326:5)
```

### PR DESCRIPTION
**Pull request by michalholasek**
#### :rocket: Why this change?
Flaky test ain't fun 👎, round two.

#### :memo: Related issues and Pull Requests
Fixes #1030

#### :white_check_mark: What didn't I forget?

- [ ] To write docs - N/A
- [ ] To write tests - N/A
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

File: src/common.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+function ignorePipeErrors(proc) {
```
Comment (honzajavorek) [inline src/common.js]: I can see the reasoning on why it's in a separate file, but in that case let's call it `ignore-pipe-errors.js` :)

File: src/ignore-pipe-errors.js [hunk 2]
```diff
@@ -1,5 +1,7 @@
 module.exports = function ignorePipeErrors(proc) {
-  proc.stdin.on('error', () => {});
-  proc.stdout.on('error', () => {});
-  proc.stderr.on('error', () => {});
+  if (proc.stdin && proc.stdout && proc.stderr) {
```
Comment (honzajavorek) [inline src/ignore-pipe-errors.js]: Shouldn't this be

```js
if (proc.stdout) { proc.stdout.on('error', () => {}); }
if (proc.stderr) { proc.stderr.on('error', () => {}); }
if (proc.stdin) { proc.stdin.on('error', () => {}); }
```

Comment (michalholasek) [reply src/ignore-pipe-errors.js]: Addressed in https://github.com/apiaryio/dredd/pull/1069/commits/f8117e78ac2dcee4b7a103733c9d215614023394.

File: src/child-process.js [hunk 3]
```diff
@@ -125,6 +127,12 @@ function terminate(childProcess, options = {}, callback) {
 const spawn = function (...args) {
   const childProcess = crossSpawn.spawn.apply(null, args);
 
+  // On Windows, killing stdin / stdout / stderr pipes intentionally
+  // on either side can result `uncaughtException` causing
+  // dredd main process exiting with exitCode 7 instead of 1. This _fix_
+  // remedies the issue.
```
[the remark this answers is not in the document]
Comment (michalholasek) [reply src/child-process.js]: https://github.com/apiaryio/dredd/pull/1069/commits/f8117e78ac2dcee4b7a103733c9d215614023394
