### PR TITLE
Fix flaky cli-test.js test case on Windows

### LINKED ISSUE #1030: Flaky test: "when using language hook handler and spawning the server and handler is killed before execution should return with status 1"
Another annoying flaky little fellow in the Windows test suite:
```
1) CLI when called with arguments when using language hook handler and spawning the server and handler is killed before execution should return with status 1:
      AssertionError: expected 7 to equal 1
      + expected - actual
      -7
      +1
      
      at Context.it (C:\projects\dredd\test\integration\cli\cli-test.js:166:56)
      at callFn (C:\projects\dredd\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\projects\dredd\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\projects\dredd\node_modules\mocha\lib\runner.js:428:10)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:534:12
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:348:14)
      at C:\projects\dredd\node_modules\mocha\lib\runner.js:358:7
      at next (C:\projects\dredd\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\projects\dredd\node_modules\mocha\lib\runner.js:326:5)
```

### PR DESCRIPTION
**Pull request by michalholasek**
#### :rocket: Why this change?
Flaky test ain't fun 👎 

#### :memo: Related issues and Pull Requests
Fixes #1030
#### :white_check_mark: What didn't I forget?

- [ ] To write docs - N/A
- [ ] To write tests - N/A
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

File: src/dredd-command.js [hunk 1]
```diff
@@ -254,6 +254,11 @@ ${packageData.name} v${packageData.version} \
         this._processExit(1);
       });
 
+      // Fixes https://github.com/apiaryio/dredd/issues/1030
+      process.stdin.on('error', (err) => {
+        logger.error(`Error in stdin: ${err}`);
+      });
```
Comment (honzajavorek) [inline src/dredd-command.js]: This is global setting (`process.stdin`) in a section of code relevant to spawning a server process. As the server process isn't the only child process Dredd spawns (server process & hook handler) and the setting influences both child processes and the Dredd process as whole, I wonder whether this shouldn't be on a common, neutral place.

Maybe `DreddCommand#constructor`?

Comment (michalholasek) [reply src/dredd-command.js]: Addressed in https://github.com/apiaryio/dredd/pull/1035/commits/b205cc9a65bb447d1ac231971a5583c9ce633878.
