### PR TITLE
Upgrade Dredd Transactions and fix tons of issues

### LINKED ISSUE #553: Support content-types with charset in Swagger's "produces"
Even if I explicitly tell in the swagger specification that the API produces something like
`application/json; charset=utf-8`, when I run dredd and my API returns a response with this content-type, Dredd tells me that it was only expecting something like `application/json` and the test breaks.

A swagger.yml example:

``` yaml
swagger: '2.0'

info:
  title: 'Example API'
  description: "Example API"
  version: '1'

host: 'api.inbenta.com'

schemes:
  - "https"

consumes:
  - "application/json; charset=utf-8"
produces:
  - "application/json; charset=utf-8"

paths:
  /validate:
    x-summary: "Verification endpoint"
    x-description: "Verifies that a token represents an authorization to apply a concrete action on a given a resource."
    get:
      parameters:
        - name: requestBody
          in: body
          required: true
          schema:
            $ref: "#/definitions/TokenAuthorizationRequest"
      responses:
        "200":
          description: "Successfully Authorized"
          schema:
            $ref: "#/definitions/SuccessResponse"
          examples:
            application/json:
              authenticated: true
              authorized: true
        "400":
          description: "Invalid request"
          schema:
            $ref: "#/definitions/GenericErrorResponse"
          examples:
            application/json:
              authenticated: true
              authorized: false
              errorMsg: "Missing request field"
        "401":
          description: "Not authenticated"
          schema:
            $ref: "#/definitions/GenericErrorResponse"
          examples:
            application/json:
              authenticated: false
              authorized: false
              errorMsg: "Invalid Token"
        "403":
          description: "Not authorized"
          schema:
            $ref: "#/definitions/GenericErrorResponse"
          examples:
            application/json:
              authenticated: true
              authorized: false
              errorMsg: "The token is not authorized to access the requested resource"
        "404":
          description: "Not found"
          schema:
            $ref: "#/definitions/GenericErrorResponse"
          examples:
            application/json:
              authenticated: true
              authorized: false
              errorMsg: "The specified resource can't be found"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/InternalServerErrorResponse"

definitions:

  TokenAuthorizationRequest:
    description: "An object to validate that a token authorizes the usage of a particular resource."
    required:
      - token
      - rcUri
      - action
    properties:
      token:
        type: string
        description: "OAuth2.0 access token"
      rcUri:
        type: string
        pattern: "^(/[A-Za-z0-9_]{1,128}){1,5}$"
        description: "REST path, identifies a resource"
      action:
        type: string
        enum: ["HEAD", "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        description: "HTTP verb, identifies an action over a resource"

  SuccessResponse:
    type: object
    required:
      - authenticated
      - authorized
    properties:
      authenticated:
        type: boolean
      authorized:
        type: boolean

  GenericErrorResponse:
    type: object
    required:
      - authenticated
      - authorized
      - errorMsg
    properties:
      authenticated:
        type: boolean
      authorized:
        type: boolean
      errorMsg:
        type: string

  InternalServerErrorResponse:
    type: object
    required:
      - errorMsg
    properties:
      errorMsg:
        type: string
```

And here the Dredd result:

```
info: Configuration './dredd.yml' found, ignoring other arguments.
info: Starting server with command: /opt/cerberus_tests/runTestServer.sh
info: Waiting 3 seconds for server command to start...
2016-07-05T09:52:58.171Z - info: [CerberusServer] Running on http://localhost:9090
info: Beginning Dredd testing...
fail: GET /validate duration: 73ms
skip: GET /validate
skip: GET /validate
skip: GET /validate
skip: GET /validate
skip: GET /validate
info: Displaying failed tests...
fail: GET /validate duration: 73ms
fail: headers: Header 'content-type' has value 'application/json; charset=utf-8' instead of 'application/json'

request: 
method: GET
uri: /validate
headers: 
    User-Agent: Dredd/1.2.0 (Linux 4.4.0-28-generic; x64)

body: 



expected: 
headers: 
    Content-Type: application/json

body: 
{
  "authenticated": true,
  "authorized": true
}
statusCode: 200
bodySchema: {"type":"object","required":["authenticated","authorized"],"properties":{"authenticated":{"type":"boolean"},"authorized":{"type":"boolean"}}}


actual: 
statusCode: 200
headers: 
    x-powered-by: Express
    content-type: application/json; charset=utf-8
    content-length: 40
    etag: W/"28-BlBhACnHg2NvLfij4Z5t+Q"
    date: Tue, 05 Jul 2016 09:53:01 GMT
    connection: close

body: 
{"authenticated":true,"authorized":true}



info: 0 passing, 1 failing, 0 errors, 5 skipped, 6 total
info: Tests took 80ms
info: Sending SIGTERM to the backend server
info: Sending SIGTERM to the backend server
info: Killing backend server

```

### LINKED ISSUE #556: Do not parse and validate body if no expectations are set and response content-length is zero or not present
I propose to do not try to parse and validate the body response in case the response `content-length` header value is `0` and the expected `body` or `bodySchema` is empty.

At the moment when your API response has JSON content type (`application/json` etc) but empty body (empty string - zero characters) Dredd tries to parse the body and it results slightly not understandable error `fail: body: Real body "Content-Type" header is "application/json" but body is not a parseble JSON.`

The zero `content-length` header is indicating the intent to do not send any data and we shouldn't expect any and assume it's ok.

Here is a temporary workaround solution with user of hooks:

``` js
var hooks = require('hooks');


// Do not parse and validate response body if the expected body and schema is empty and the response 
// header content-type is zero or not present regardless the response content-type
hooks.beforeEachValidation(function(transaction){
  var body = transaction['expected']['body'];
  var bodySchema = transaction['expected']['bodySchema'];

  var isBodyEmpty = body == null || body == undefined || body == ''
  var isBodySchemaEmpty = bodySchema == null || bodySchema == undefined || bodySchema == ''

  if(isBodyEmpty && isBodySchemaEmpty){

    //caseless lookup for the content-length header key
    var contentLengthKey = null;
    var responseHeaderKeys = Object.keys(transaction['real']['headers']);
    responseHeaderKeys.forEach(function(responseHeaderKey){
      if(responseHeaderKey.toLowerCase() == 'content-length'){
        contentTypeKey = responseHeaderKey;
      };
    });

    var contentLength = null;
    // if response has content-length
    if(contentLengthKey !== null){
      var contentLength = parseInt(transacation['real']['headers'][contetLengthKey],10);
    }

    if(contentLengthKey === null || conetntLength === 0){
      //skip the body validation the way mentioned in https://github.com/apiaryio/dredd/issues/510
      hooks.log("skipping body validation")
      transaction['expected']['body'] = undefined;
      transaction['expected']['bodySchema'] = undefined;
    };
  };
});
```

### LINKED ISSUE #711: Test request's body is empty in the case of a multipart/form-data request with Swagger 2.0 Document
#### Describe your problem
Hi,

I try to use Dredd to tests our API's spec written in Swagger 2.0 format. The test generated by Dredd to test a multipart/form-data request fails to generated the body of the request. And the multipart/form-data definition is interpreted as "application/x-www-form-urlencoded". There are warnings who seem to say the the multipart is not well supported. Is it the case? Is there any work-around to this problem ?

```
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Only the first scheme will be used to create a hostname on line 12
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17

request: 
method: POST
uri: /firstMethod
headers: 
    Accept: application/json
    Content-Type: application/x-www-form-urlencoded
    User-Agent: Dredd/2.2.5 (Linux 3.19.0-79-generic; x64)

body: 



expected: 
headers: 
    Content-Type: application/json

body: 
[
  {
    "success": true,
    "id": 123456
  }
]
statusCode: 200

```

Thank you

#### What command line options do you use?
```
$ docker run -v /home/user/Projects/swagger:/tmp/swagger 6d5c665ea96c dredd /tmp/swagger/api.yaml http://10.107.7.198:8081/
```

#### What is in your `dredd.yml`?

```yaml
swagger: '2.0'
info:
  title: My API
  description: blabalbal
  version: "1.0.0"
host: my.api.com
basePath: /
tags:
  -
    name: "First Function"
    description: "Blablabla"
schemes:
  - https
  - http
paths:
  /firstMethod:
    post:
      summary: blablabla
      description: |
        blablablabla.
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: param1
          in: formData
          description: blabla param1
          type: number
          format: int64
          required: true
        - name: param2
          in: formData
          description: blabla param2
          type: number
          format: int64
          required: true
        - name: param2
          in: formData
          description: blabla param2
          type: string
          required: true
        - name: param3
          in: formData
          description: blabla param3.
          type: file
          required: true
        - name: param4
          in: formData
          description: blabla param4.
          type: string
          format: string
          required: false
        - name: param5
          in: formData
          description: blabla param5.
          type: number
          format: int64
          required: false
        - name: param6
          in: formData
          description: blabla param6
          type: string
          required: false
        - name: param7
          in: formData
          description: blabla param7
          type: string
          required: false
      responses:
        200:
          description: Successful response
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/ResultSuccess'
          examples:
            application/json:
              -
                success: true
                id: 123456
        400:
          description: |
            Bad Request response

            4001	INCORRECT PARAMETERS

            4101	TYPE ERROR 1

            4102	TYPE ERROR 2

            4103	TYPE ERROR 3

            4201	TYPE ERROR 4

            4202	TYPE ERROR 5

            4203	TYPE ERROR 6
          schema:
            $ref: '#/definitions/ResultError'
          examples:
            application/json:
              -
                success: false
                code: "4001"
                error: "INCORRECT PARAMETERS"
        500:
          description: |
            Internal Server Error response

            5000	INTERNAL ERROR
          schema:
            $ref: '#/definitions/ResultError'
          examples:
            application/json:
              -
                success: false
                code: "5000"
                error: "INTERNAL ERROR"
definitions:
  ResultSuccess:
    type: object
    properties:
      success:
        type: boolean
        description: If transaction created succesfully.
      id:
        type: number
        description: Unique identifier.
  ResultError:
    type: object
    properties:
      success:
        type: boolean
        description: If transaction created succesfully.
      code:
        type: string
        description: Code of the errors
      error:
        type: string
        description: Error message
```

#### What's your `dredd --version` output?
```
dredd v2.2.5 (Linux 3.19.0-79-generic; x64)
```

#### Does `dredd --level=debug` uncover something?
Nothing more interessting uncoverred.
You have the full trace below:
```
verbose: Loading configuration file: ./dredd.yml
debug: Dredd version: 2.2.5
debug: Node.js version: v4.4.7
debug: Node.js environment: http_parser=2.5.2, node=4.4.7, v8=4.5.103.36, uv=1.8.0, zlib=1.2.8, ares=1.10.1-DEV, modules=46, openssl=1.0.2h
debug: System version: Linux 3.19.0-79-generic x64
debug: npm version: 2.15.9
debug: Configuration: {"server":"http://10.107.7.198:8081/","options":{"_":["/tmp/swagger/api.yaml"],"level":"debug","l":"debug","dry-run":null,"y":null,"hookfiles":null,"f":null,"language":"nodejs","a":"nodejs","sandbox":false,"b":false,"server":null,"g":null,"server-wait":3,"init":false,"i":false,"custom":{},"j":[],"names":false,"n":false,"only":[],"x":[],"reporter":[],"r":[],"output":[],"o":[],"header":[],"h":[],"sorted":false,"s":false,"user":null,"u":null,"inline-errors":false,"e":false,"details":false,"d":false,"method":[],"m":[],"color":true,"c":true,"timestamp":false,"t":false,"silent":false,"q":false,"path":["/tmp/swagger/api.yaml","/tmp/swagger/api.yaml"],"p":["/tmp/swagger/api.yaml","/tmp/swagger/api.yaml"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"localhost","hooks-worker-handler-port":61321,"config":"./dredd.yml","$0":"/usr/bin/node /node_modules/.bin/dredd"},"custom":{"cwd":"/","argv":["/tmp/swagger/api.yaml","http://10.107.7.198:8081/","--level=debug"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: No backend server process specified, starting testing at once.
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
verbose: Reading API description files.
verbose: Parsing API description files and compiling a list of HTTP transactions to test.
verbose: Compiling HTTP transactions from API description file: /tmp/swagger/api.yaml
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Only the first scheme will be used to create a hostname on line 12
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Files in form parameters are not fully supported yet on line 43
warn: Parser warning in file '/tmp/swagger/api.yaml': (warning code 3) Unable to generate application/x-www-form-urlencoded example message body out of JSON Schema on line 17
verbose: Starting reporters and waiting until all of them are ready.
info: Beginning Dredd testing...
verbose: Starting transaction runner.
verbose: Sorting HTTP transactions
verbose: Configuring HTTP transactions
verbose: Reading hook files and registering hooks
verbose: Executing HTTP transactions
verbose: Running 'beforeAll' hooks
debug: Running hooks...
verbose: Processing transaction #1: /firstMethod > balbalbal > 200 > application/json
verbose: Running 'beforeEach' hooks
debug: Running hooks...
verbose: Running 'before' hooks
debug: Emitting to reporters: test start
verbose: About to perform an HTTP request to tested server
verbose: Handling HTTP response from tested server
debug: Response from tested server was recieved
verbose: Running 'beforeEachValidation' hooks
debug: Running hooks...
verbose: Running 'beforeValidation' hooks
verbose: Validating HTTP transaction by Gavel.js
debug: Determining whether HTTP transaction is valid (getting boolean verdict)
debug: Validating HTTP transaction (getting verbose validation result)
verbose: Running 'afterEach' hooks
debug: Running hooks...
verbose: Running 'after' hooks
debug: Evaluating results of transaction execution #1: /firstMethod > balbalbal > 200 > application/json
debug: Emitting to reporters: test fail
fail: POST /firstMethod duration: 118ms
verbose: Processing transaction #2: /firstMethod > balbalbal > 400 > application/json
verbose: Running 'beforeEach' hooks
debug: Running hooks...
verbose: Running 'before' hooks
debug: Emitting to reporters: test start
verbose: HTTP transaction was marked in hooks as to be skipped. Skipping
verbose: Running 'afterEach' hooks
debug: Running hooks...
verbose: Running 'after' hooks
debug: Evaluating results of transaction execution #2: /firstMethod > balbalbal > 400 > application/json
debug: Emitting to reporters: test skip
skip: POST /firstMethod
verbose: Processing transaction #3: /firstMethod > balbalbal > 500 > application/json
verbose: Running 'beforeEach' hooks
debug: Running hooks...
verbose: Running 'before' hooks
debug: Emitting to reporters: test start
verbose: HTTP transaction was marked in hooks as to be skipped. Skipping
verbose: Running 'afterEach' hooks
debug: Running hooks...
verbose: Running 'after' hooks
debug: Evaluating results of transaction execution #3: /firstMethod > balbalbal > 500 > application/json
debug: Emitting to reporters: test skip
skip: POST /firstMethod
verbose: Running 'afterAll' hooks
debug: Running hooks...
verbose: Wrapping up testing.
info: Displaying failed tests...
fail: POST /firstMethod duration: 118ms
fail: headers: Header 'content-type' has value 'text/plain' instead of 'application/json'
statusCode: Status code is not '200'

request: 
method: POST
uri: /firstMethod
headers: 
    Accept: application/json
    Content-Type: application/x-www-form-urlencoded
    User-Agent: Dredd/2.2.5 (Linux 3.19.0-79-generic; x64)

body: 



expected: 
headers: 
    Content-Type: application/json

body: 
[
  {
    "success": true,
    "id": 123456
  }
]
statusCode: 200
bodySchema: {"type":"object","properties":{"success":{"type":"boolean","description":"If transaction created succesfully."},"id":{"type":"number","description":"Unique identifier."}}}


actual: 
statusCode: 400
headers: 
    access-control-allow-origin: *
    content-type: text/plain
    transfer-encoding: chunked

body: 
{"code":"4001","error":"INCORRECT PARAMETERS","success":false}



complete: 0 passing, 1 failing, 0 errors, 2 skipped, 3 total
complete: Tests took 128ms
verbose: Dredd instance run finished.
verbose: Exiting Dredd process with status '1'.
debug: Using configured custom exit() method to terminate the Dredd process.
verbose: Gracefully terminating backend server process.
verbose: No backend server process.

```

#### Can you send us failing test in a Pull Request?
Is it necessary in my case? And how ?

### LINKED ISSUE #893: Dredd crashes on Petstore example
#### Describe your problem

In order to evaluate `dredd` I have tried it on the [Petstore](http://petstore.swagger.io) example and I got a failure with the following error message:

```
error: Cannot read property 'toValue' of undefined
```

#### What command line options do you use?

```
$ dredd http://petstore.swagger.io/v2/swagger.json http://petstore.swagger.io/v2 --level debug
```

#### What is in your `dredd.yml`?

I did not use any configuration file.

#### What's your `dredd --version` output?

```
dredd v4.5.0 (Darwin 16.7.0; x64)
```

#### Does `dredd --level=debug` uncover something?

Nope, the output is as follows:

```
verbose: Loading configuration file: ./dredd.yml
debug: Dredd version: 4.5.0
debug: Node.js version: v8.6.0
debug: Node.js environment: http_parser=2.7.0, node=8.6.0, v8=6.0.287.53, uv=1.14.1, zlib=1.2.11, ares=1.10.1-DEV, modules=57, nghttp2=1.25.0, openssl=1.0.2l, icu=59.1, unicode=9.0, cldr=31.0.1, tz=2017b
debug: System version: Darwin 16.7.0 x64
debug: npm version: 5.3.0
debug: Configuration: {"server":"http://petstore.swagger.io/v2","options":{"_":["http://petstore.swagger.io/v2/swagger.json"],"level":"debug","l":"debug","color":false,"c":"false","dry-run":null,"y":null,"hookfiles":null,"f":null,"language":"nodejs","a":"nodejs","sandbox":false,"b":false,"server":null,"g":null,"server-wait":3,"init":false,"i":false,"custom":{},"j":[],"names":false,"n":false,"only":[],"x":[],"reporter":[],"r":[],"output":[],"o":[],"header":[],"h":[],"sorted":false,"s":false,"user":null,"u":null,"inline-errors":false,"e":false,"details":false,"d":false,"method":[],"m":[],"timestamp":false,"t":false,"silent":false,"q":false,"path":["http://petstore.swagger.io/v2/swagger.json","http://petstore.swagger.io/v2/swagger.json"],"p":["http://petstore.swagger.io/v2/swagger.json","http://petstore.swagger.io/v2/swagger.json"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"./dredd.yml","$0":"/usr/local/bin/dredd"},"custom":{"cwd":"/Users/bagrat/sauce/sauce/hostess/resto","argv":["http://petstore.swagger.io/v2/swagger.json","http://petstore.swagger.io/v2","--level","debug","--color","false"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: No backend server process specified, starting testing at once
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
verbose: Reading API description files.
verbose: Downloading remote file: http://petstore.swagger.io/v2/swagger.json
verbose: Parsing API description files and compiling a list of HTTP transactions to test.
verbose: Compiling HTTP transactions from API description file: http://petstore.swagger.io/v2/swagger.json
verbose: Dredd instance run finished.
error: Cannot read property 'toValue' of undefined
verbose: Exiting Dredd process with status '1'.
debug: Using native process.exit() method to terminate the Dredd process.
verbose: No backend server process to terminate.
```

#### Can you send us failing test in a Pull Request?

Not yet 😢

### LINKED ISSUE #897: Infer default JSON Schema in Swagger (can't validate. Expected body Content-Type is application/json but body is not a parseable JSON)
#### Describe your problem

Dredd reports:

>Can't validate. Expected body Content-Type is application/json but body is not a parseable JSON: Parse error on line 1: ^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

when the response JSON is present and valid but the Swagger `responseObject` does not contain a `schema`, so this error text is misleading. It may refer to parsing the schema, not the response.

#### What command line options do you use?

```
$ npx dredd 
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: node index.js
server-wait: 3
init: false
custom:
  apiaryApiKey: ''
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./contract/swagger.json
endpoint: 'http://127.0.0.1:3001'
```

#### What's your `dredd --version` output?

```
dredd v4.5.0 (Windows_NT 10.0.15063; x64)
```

#### Does `dredd --level=debug` uncover something?

https://gist.github.com/MikeRalphson/2b3c35bc05ad9009e4b9c4eaeda48444

There is a line `debug: Could not stringify:`

#### Can you send us failing test in a Pull Request?

To follow if required once I've looked at test structure.

As mentioned in #461 

* Minimal valid [swagger definition](https://gist.github.com/MikeRalphson/ebf3aa8f8c46246305921cc5a6a09558)
* [Failing test](https://app.apiary.io/bbcibl/tests/run/63c79d51-bce7-4f50-b8ff-cd4957ff4624)
* [Passing test](https://app.apiary.io/bbcibl/tests/run/1a695410-9523-4761-9a6c-a1ce7145ed64)

The only change required to make the test pass is the following diff to the swagger definition:

```diff
--- contract/min.json   2017-10-18 08:41:09.693730500 +0100
+++ contract/minplus.json       2017-10-18 08:46:48.036825400 +0100
@@ -27,7 +27,8 @@
                 ],
                 "responses": {
                     "200": {
-                        "description": "default"
+                        "description": "default",
+                        "schema": {}
                     }
                 }
             }
```

### LINKED ISSUE #905: Installation failure because of peer dependencies.
I'm attempting to install Dredd but I am getting a `EPEERINVALID` error when installing with `npm install -g dredd`:

```
/usr/bin/dredd -> /usr/lib/node_modules/dredd/bin/dredd
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "dredd"
npm ERR! node v4.8.5
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package fury@3.0.0-beta.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fury-adapter-apib-parser@0.9.0 wants fury@3.0.0-beta.4
npm ERR! peerinvalid Peer fury-adapter-swagger@0.13.4 wants fury@3.0.0-beta.4

npm ERR! Please include the following file with any support request:
npm ERR!     /groot/npm-debug.log```

### PR DESCRIPTION
**Pull request by honzajavorek**
#### :rocket: Why this change?

- Solitary default responses in Swagger are now treated as HTTP 200 #893
- Fixes how Dredd handles empty bodies and empty schemas #556, #897
- Pins peer dependencies #905
- In Swagger, JSON media types with parameters (such as charset) are now recognized as JSON #553, #883
- Fixed handling of multipart/form-data in Swagger #711

#### :memo: Related issues and Pull Requests

- Closes https://github.com/apiaryio/dredd/pull/896 (deprecates)
- Fixes #893, fixes #556, fixes #897, fixes #905, fixes #711, fixes #553
- Related https://github.com/apiaryio/dredd/issues/883, https://github.com/apiaryio/dredd-transactions/pull/119

#### :white_check_mark: What didn't I forget?

- [x] Incorporate https://github.com/apiaryio/dredd/pull/896
- [x] To write docs for empty bodies and empty schemas
- [x] To write docs on how to assert empty bodies, assertions from body/schema
- [x] To write docs for solitary default responses
- [x] To write docs for `multipart/form-data` handling
- [x] To write docs for which produces media types are (not) ignored, how to create non-JSON media types
- [x] To write tests for solitary default responses (in Dredd Transactions)
- [x] To write tests for empty bodies and empty schemas
- [x] Test HTTP 204, 205
- [x] To write tests for `application/json; charset=utf-8` (in Dredd Transactions)
- [x] To write tests for `multipart/form-data` handling
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

**Comment by honzajavorek** [comment]
Note for myself: I made some notes on paper, which I should turn into To Do here.

File: src/transaction-runner.coffee [hunk 1]
```diff
@@ -36,16 +36,15 @@ class TransactionRunner
     transactions = if @configuration.options['sorted'] then sortTransactions(transactions) else transactions
 
     logger.verbose('Configuring HTTP transactions')
-    async.mapSeries transactions, @configureTransaction.bind(@), (err, results) =>
-      transactions = results
+    transactions = transactions.map(@configureTransaction.bind(@))
```
Comment (honzajavorek) [inline src/transaction-runner.coffee]: I made unrelated change - I changed the `configureTransaction()` method to be synchronous (because there was nothing async inside...). It looked like a small change, but then I realised I broke a lot of unit tests 🙈 Anyway, I'm sorry for that. I should have send that separately.

File: src/transaction-runner.coffee [hunk 2]
```diff
@@ -111,8 +110,8 @@ class TransactionRunner
 
   # The 'data' argument can be 'transactions' array or 'transaction' object
   runHooksForData: (hooks, data, legacy = false, callback) ->
-    if hooks? and Array.isArray hooks
-      logger.debug 'Running hooks...'
+    if hooks?.length
```
Comment (honzajavorek) [inline src/transaction-runner.coffee]: This is unrelated change as well. When there are no hooks, this method should skip directly to callback, not to feed `async.timesSeries()` with zero... I'm also guilty here for not sending this separately.

File: src/transaction-runner.coffee [hunk 3]
```diff
@@ -274,7 +272,7 @@ class TransactionRunner
     if typeof(hook) == 'string'
       @runSandboxedHookFromString hook, data, callback
 
-  configureTransaction: (transaction, callback) =>
+  configureTransaction: (transaction) =>
```
Comment (honzajavorek) [inline src/transaction-runner.coffee]: This is unrelated change, see https://github.com/apiaryio/dredd/pull/906/files#r152850808

File: test/unit/transaction-runner-test.coffee [hunk 4]
```diff
@@ -96,7 +96,7 @@ describe 'TransactionRunner', ->
 
         assert.isOk runner.multiBlueprint
 
-  describe 'configureTransaction(transaction, callback)', ->
+  describe 'configureTransaction(transaction)', ->
```
Comment (honzajavorek) [inline test/unit/transaction-runner-test.coffee]: This is unrelated change, see https://github.com/apiaryio/dredd/pull/906/files#r152850808

**Comment by honzajavorek** [comment]
@michalholasek I'm thinking maybe some of the regression tests I've been writing as the first ones are now superseded by normal integration tests I wrote later on. Also, some could become normal integration tests, instead of regression tests. Up to you. Also, we can do it as a next step, if you think it's a good idea.

File: appveyor.yml [hunk 5]
```diff
@@ -6,7 +6,7 @@ install:
   - "set PATH=%APPDATA%\\npm;%PATH%"
   - "npm install --no-optional"
 cache:
-  - "node_modules"
+  - "node_modules -> package.json"
```
Comment (michalholasek) [inline appveyor.yml]: Just a note: Interesting syntax for cache wipe 🙂

File: test/integration/regressions/regression-893-897-test.coffee [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+
+Dredd = require('../../../src/dredd')
+{runDreddWithServer, createServer} = require('../helpers')
+
+
+describe('Regression: Issue #893 and #897', ->
+  describe('when the response has no explicit status code', ->
+    runtimeInfo = undefined
+
+    beforeEach((done) ->
```
Comment (michalholasek) [inline test/integration/regressions/regression-893-897-test.coffee]: I don't think it is necessary to use `beforeEach` here (use `before`), the server is the same for each assertion.

File: test/fixtures/response/empty-body-hooks.js [hunk 7]
```diff
@@ -0,0 +1,9 @@
+var hooks = require('hooks');
+
+
```
Comment (michalholasek) [inline test/fixtures/response/empty-body-hooks.js]: NIT: I don't like this empty space 🛰

File: test/integration/response-test.coffee [hunk 8]
```diff
@@ -0,0 +1,341 @@
+{assert} = require('chai')
+
+{runDreddWithServer, createServer} = require('./helpers')
+Dredd = require('../../src/dredd')
+
+
```
Comment (michalholasek) [inline test/integration/response-test.coffee]: NIT: I don't like this empty space 🛰

File: test/integration/response-test.coffee [hunk 9]
```diff
@@ -0,0 +1,341 @@
...
+    path: './test/fixtures/response/empty-body-empty-schema.apib'
+  ,
+    name: 'Swagger'
+    path: './test/fixtures/response/empty-body-empty-schema.yaml'
+].forEach((apiDescription) ->
+  describe("Specifying neither response body nor schema in the #{apiDescription.name}", ->
+    describe('when the server returns non-empty responses', ->
+      runtimeInfo = undefined
+
+      beforeEach((done) ->
```
Comment (michalholasek) [inline test/integration/response-test.coffee]: I think that server creation for this and subsequent `describe`'s can be moved to upper scope and reused for all assertions, correct? Small things like this add up and are slowly degradeting performance of our test suite.

File: test/integration/response-test.coffee [hunk 10]
```diff
@@ -0,0 +1,341 @@
...
+    path: './test/fixtures/response/empty-body-empty-schema.apib'
+  ,
+    name: 'Swagger'
+    path: './test/fixtures/response/empty-body-empty-schema.yaml'
+].forEach((apiDescription) ->
+  describe("Specifying no response body in the #{apiDescription.name} and having hooks ensuring empty response", ->
+    describe('when the server returns a non-empty responses', ->
+      runtimeInfo = undefined
+
+      beforeEach((done) ->
```
Comment (michalholasek) [inline test/integration/response-test.coffee]: Same as previous comment (move server creation to upper scope and reuse it for all assertions, since it is the same for all of them).

File: test/integration/request-test.coffee [hunk 11]
```diff
@@ -41,85 +41,105 @@ describe('Sending \'application/json\' request', ->
...
+      app = createServer({bodyParser: bodyParser.text({type: contentType})})
+      app.post('/data', (req, res) ->
+        res.json({test: 'OK'})
+      )
+      dredd = new Dredd({options: {path: apiDescription.path}})
+
+      runDreddWithServer(dredd, app, (err, info) ->
+        runtimeInfo = info
+        done(err)
+      )
```
Comment (michalholasek) [inline test/integration/request-test.coffee]: Again, dummy server is created for each assertion. I think it is not necessary to create the same server over and over again (aka use `before`, not `beforeEach`) 🙂

**Comment by honzajavorek** [comment]
Regarding blank lines, that's fight topic 😏 Airbnb [doesn't say anything about them](https://github.com/airbnb/javascript), so I'm free to choose. And I chose to follow [this](https://www.python.org/dev/peps/pep-0008/#blank-lines):

> Surround top-level function and class definitions with two blank lines.
> Method definitions inside a class are surrounded by a single blank line.

File: test/integration/response-test.coffee (hunk 9 above)
Comment (honzajavorek) [reply test/integration/response-test.coffee]: I'm definitely for using `before` where it makes sense, but I wouldn't share `before` blocks between multiple `describe`s, as I think that's over the line of keeping the tests isolated. You don't want to go that way, it easily erodes.

**Comment by honzajavorek** [comment]
I added 5a436ff with `beforeEach` -> `before` in the affected integration and most regression tests. There was one regression test which looked like it's one of the older ones, so I rather didn't touch that one 👀

File: appveyor.yml (hunk 5 above)
Comment (honzajavorek) [reply appveyor.yml]: Yup, didn't know about it :) AppVeyor has some pretty cool features.
