### PR TITLE
test: uses "hasAllKeys" for order-insensitive keys assertion

### LINKED ISSUE #1368: Order assertion of results keys in sanitization test
**Describe the bug**
In the current `sanitization-test.js` we assert that the validation result has all the specified keys:

https://github.com/apiaryio/dredd/blob/306528427176c6b6d3f7e2eed8a27afdd5b063b7/test/integration/sanitation-test.js#L497

However, we achieve that through `deepEqual`, which makes the order of keys matter.

**To Reproduce**
```bash
mocha test/integration/sanitation-test.js
```

**Expected behavior**
We should assert that `event[2].test.results` contains all the keys, without relying on the exact order of keys. I suggest to use `hasAllKeys` instead:

```js
assert. hasAllKeys(events[2].test.results, ['general', 'headers', 'body', 'statusCode']);
```

**What is in your `dredd.yml`?**

Doesn't influence the issue.

**What's your `dredd --version` output?**

```
11.1.0
```

> Internally, this issue has occurred because the order of validation changed in `gavel`. However, this may be a good chance to re-consider certain tests to be bulletproof.

### PR DESCRIPTION
**Pull request by artem-zakharchenko**
#### :rocket: Why this change?

Uses `hasAllKeys` for assertion of validation results object keys in sanitization tests. Makes assertion order-insensitive, improving the tests' sustainability. Also fixes a logical flaw where object's keys are asserted in specific order.

#### :memo: Related issues and Pull Requests

- Fixes #1368 

#### :white_check_mark: What didn't I forget?

- [x] To write docs
- [x] To write tests
- [x] To put [Conventional Changelog](https://dredd.org/en/latest/internals.html#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

File: test/integration/sanitation-test.js [hunk 1]
```diff
@@ -494,7 +494,8 @@ describe('Sanitation of Reported Data', () => {
       assert.equal(events[2].test.status, 'fail');
       assert.include(events[2].test.results.general.results[0].message.toLowerCase(), 'fail');
     });
-    it('emitted test data results contain all regular sections', () => assert.deepEqual(Object.keys(events[2].test.results), ['general', 'headers', 'body', 'statusCode']));
+    it('emitted test data results contain all regular sections', () => assert.hasAllKeys(events[2
+    ].test.results, ['general', 'headers', 'body', 'statusCode']));
```
Comment (honzajavorek) [inline test/integration/sanitation-test.js]: Strange newline, but given the test is decaffeinated and not humanly formatted, this is a minor issue.

Comment (artem-zakharchenko) [reply test/integration/sanitation-test.js]: Fixed. Thanks :)
