### PR TITLE
Throw error when additional path doesn't exist

### LINKED ISSUE #378: If additional files are given in --path and they don't exist, Dredd silently ignores them
Is this bug or feature? In case Dredd should ignore them, it should be documented and there should be at least warning logged. In case Dredd should fail, then it does not and it's a bug.

``` shell
$ ls
apiary.apib
$ dredd ./apiary.apib http://localhost:8000 --path=./non-existent.apib
...
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by honzajavorek**
#### :rocket: Why this change?

Dredd should treat non-existing files (or globs evaluating to no files) as user error. This PR just finalizes @jgjadaoag's amazing work in https://github.com/apiaryio/dredd/pull/909.

We want to have this done as soon as possible so there are no open Pull Requests and we could decaf the codebase - #705.

#### :memo: Related issues and Pull Requests

- Fixes #378
- Closes https://github.com/apiaryio/dredd/pull/909

#### :white_check_mark: What didn't I forget?

- [ ] ~~To write docs~~
- [x] To write tests
- [x] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

File: src/add-hooks.coffee [hunk 1]
```diff
@@ -101,30 +101,38 @@ addHooks = (runner, transactions, callback) ->
...
-    )
+    try
+      files = hookfiles.reduce((result, unresolvedPath) ->
+        # glob.sync does not resolve paths, only glob patterns
+
+        unresolvedPaths = if glob.hasMagic(unresolvedPath) then glob.sync(unresolvedPath) else
+          if fs.existsSync(unresolvedPath) then [unresolvedPath] else []
+
+        if unresolvedPaths.length == 0
+          throw new Error("Hook file(s) not found on path: #{unresolvedPath}")
```
Comment (michalholasek) [inline src/add-hooks.coffee]: I don't like the fact that `throw new Error(...)` is used inside a `reduce` method. I would rather seen it rewritten in `forEach` or some imperative equivalent.

Comment (honzajavorek) [reply src/add-hooks.coffee]: I added some commits. Not sure if I actually addressed this comment though, because the resulting flow avoids reduce, but now the `throw` still happens in a `.map()` iteratee.

I think throwing exceptions isn't anything a pure function couldn't do. It's not mutation, it's just one of the possible outcomes of the pure function.
