### PR TITLE
fix: uses explicit validation result sections list for logging output

### LINKED ISSUE #1371: Logging order in transaction runner depends on Gavel's validation order
**Describe the bug**
The order in which the validation result is logged directly depends on the order in which validation is executed in Gavel (see https://github.com/apiaryio/gavel.js/issues/169). This is not okay, since it creates a tight dependency between two libraries, making Dredd fail if Gavel suddenly returns validation results in a different order.

In the mentioned Gavel's issue I reason why the order must never be relied on, and Dredd should specify the required order within its logging.

**To Reproduce**

```
mocha test/integration/response-test.js
```

Execute the test suite and see it pass. Change the order of validators invocation in Gavel and see it fail.

**Expected behavior**
- No tight dependency between Gavel and Dredd order of validators
- Dredd specifies an explicit list of "sections" it outputs during the logging

**What's your `dredd --version` output?**

```
11.1.0
```

### PR DESCRIPTION
**Pull request by artem-zakharchenko**
#### :rocket: Why this change?

Introduces an explicit list of validation result sections to be present in the Dredd's transaction runner output. This allows Dredd to be independent from Gavel's validation order, and also makes it resilient to new Gavel releases.

#### :memo: Related issues and Pull Requests

- Fixes #1371

#### :white_check_mark: What didn't I forget?

- [x] To write docs
- [x] To write tests
- [x] To put [Conventional Changelog](https://dredd.org/en/latest/internals.html#sem-rel) prefixes in front of all my commits and run `npm run lint`

### CODE REVIEW

File: lib/TransactionRunner.js [hunk 1]
```diff
@@ -572,16 +572,20 @@ include a message body: https://tools.ietf.org/html/rfc7231#section-6.3\
...
         let message = '';
         const object = gavelResult || {};
+
         let validatorOutput;
-        for (const sectionName of Object.keys(object || {})) {
-          // Section names are 'statusCode', 'headers', 'body' (and 'version', which is irrelevant)
+
+        // Order-sensitive list of validation sections to output in the log
+        const resultSections = ['headers', 'body', 'statusCode']
+          .filter(sectionName => Object.prototype.hasOwnProperty.call(gavelResult, sectionName));
```
Comment (artem-zakharchenko) [inline lib/TransactionRunner.js]: Since now we have an explicit list of sections we need to filter out those sections that are actually present in the Gavel's results.
